# Generated by Django 5.0 on 2025-04-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('reviewed', 'Проверено')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(upload_to='solutions/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
