# Generated by Django 5.0 on 2025-04-29 12:18

import django.db.models.deletion
import olympiad.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_olympiads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], max_length=10),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='rules',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='statement_file',
            field=models.FileField(upload_to='statements/', validators=[olympiad.models.validate_pdf]),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Студент'), ('teacher', 'Преподаватель'), ('admin', 'Администратор')], default='student', max_length=10)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
