# Generated by Django 5.0 on 2025-04-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0002_olympiad_creator_olympiad_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='additional_info',
            field=models.TextField(blank=True, max_length=500, verbose_name='Дополнительные сведения'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Фото профиля'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.CharField(blank=True, max_length=100, verbose_name='Организация/Учебное заведение'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Должность/Группа'),
        ),
    ]
