# Generated by Django 5.0 on 2025-04-29 13:18

import olympiad.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0003_userprofile_additional_info_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='statement_file',
            field=models.FileField(upload_to='statements/', validators=[olympiad.models.validate_file_size]),
        ),
    ]
